In [1]:
import numpy as np

alpha = 0.9
gamma = 0.75

In [2]:
location_to_state = {'A': 0,
                     'B': 1,
                     'C': 2,
                     'D': 3,
                     'E': 4,
                     'F': 5,
                     'G': 6,
                     'H': 7,
                     'I': 8,
                     'J': 9,
                     'K': 10,
                     'L': 11}

In [3]:
actions = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [36]:
R = np.array([ [0,1,0,0,0,0,0,0,0,0,0,0],
             [1,0,1,0,0,1,0,0,0,0,0,0],
             [0,1,0,0,0,0,1,0,0,0,0,0],
             [0,0,0,0,0,0,0,1,0,0,0,0],
             [0,0,0,0,0,0,0,0,1,0,0,0],
             [0,1,0,0,0,0,0,0,0,1,0,0],
             [0,0,1,0,0,0,1,10,0,0,0,0],
             [0,0,0,1,0,0,1,0,0,0,0,1],
             [0,0,0,0,1,0,0,0,0,1,0,0],
             [0,0,0,0,0,1,0,0,1,0,1,0],
             [0,0,0,0,0,0,0,0,0,1,0,1],
             [0,0,0,0,0,0,0,1,0,0,1,0]])

In [37]:
Q = np.array(np.zeros([12, 12]))

In [38]:
for i in range(1000):
    current_state = np.random.randint(0, 12)
    playable_actions = []
    for j in range(12):
        if R[current_state, j] > 0:
            playable_actions.append(j)
    next_state = np.random.choice(playable_actions)
    TD = R[current_state, next_state] + gamma * Q[next_state, np.argmax(Q[next_state,])] - Q[current_state, next_state]
    Q[current_state, next_state] = Q[current_state, next_state] + alpha * TD

In [39]:
print(Q.astype(int))

[[ 0 12  0  0  0  0  0  0  0  0  0  0]
 [10  0 15  0  0 10  0  0  0  0  0  0]
 [ 0 12  0  0  0  0 19  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 15  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  7  0  0  0]
 [ 0 12  0  0  0  0  0  0  0  8  0  0]
 [ 0  0 15  0  0  0 19 24  0  0  0  0]
 [ 0  0  0 12  0  0 19  0  0  0  0 12]
 [ 0  0  0  0  6  0  0  0  0  8  0  0]
 [ 0  0  0  0  0 10  0  0  7  0 10  0]
 [ 0  0  0  0  0  0  0  0  0  8  0 12]
 [ 0  0  0  0  0  0  0 15  0  0 10  0]]


In [40]:
state_to_location = {state: location for location, state in location_to_state.items()}

In [41]:
def route(starting_location, ending_location):
     route = [starting_location]
     next_location = starting_location
     while (next_location != ending_location):
         starting_state = location_to_state[starting_location]
         next_state = np.argmax(Q[starting_state,])
         next_location = state_to_location[next_state]
         route.append(next_location)
         starting_location = next_location
     return route

In [42]:
print('Route:')
route('E', 'G')

Route:


['E', 'I', 'J', 'F', 'B', 'C', 'G']